<?php

namespace MailPoetVendor;

if (!defined('ABSPATH')) exit;


// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInitdf50864ba094a78742fdc9f90862b57f::getLoader();
