/*
 * Sticky Radio Player - Full Width Shoutcast and Icecast HTML5 Player - v2.3
 *
 * Copyright 2016-2020, LambertGroup
 *
 */

 (function(d){function K(a,c,g,e){d(a.thumbsHolder_Thumbs[a.current_img_no]).css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor});a.is_very_first||C(-1,a,c,g);var m;""!=a.playlist_arr[a.origID].radiostream&&(m=a.playlist_arr[a.origID].radiostream);return m}function M(a,c,g,e,m){m=c.noImageAvailable;var f="",l="";if(""!=a&&void 0!=a){f=a.match(/\.([^\./\?#]+)($|\?|#)/)[1];if("jpg"==f||"jpeg"==f||"JPG"==f||"JPEG"==f)l=
 "&iiurlparam=qlow-500px";d.get("https://commons.wikimedia.org/w/api.php?action=query&titles=Image:"+a+"&prop=imageinfo&format=xml&origin=*&iiprop=url"+l,{},function(a){""!=d("ii",a).attr("thumburl")&&void 0!=d("ii",a).attr("thumburl")?(m=d("ii",a).attr("thumburl"),g.wiki_photo_path=m):""!=d("ii",a).attr("url")&&void 0!=d("ii",a).attr("url")&&(m=d("ii",a).attr("url"),g.wiki_photo_path=m);P(c,g,e,m)})}}function S(a){a=a.split("");a.forEach(function(c,d){var e="\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4\u00e5\u00df\u00d2\u00d3\u00d4\u00d5\u00d5\u00d6\u00d8\u00f2\u00f3\u00f4\u00f5\u00f6\u00f8\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u00f0\u00c7\u00e7\u00d0\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u00d1\u00f1\u0160\u0161\u0178\u00ff\u00fd\u017d\u017e\u2019".indexOf(c);
 -1!=e&&(a[d]="AAAAAAaaaaaaBOOOOOOOooooooEEEEeeeeeCcDIIIIiiiiUUUUuuuuNnSsYyyZz'"[e])});return a.join("").trim()}function N(a,c,g,e,m,f,l,w,k,r){clearInterval(a.radioReaderAjaxInterval);d.get(c.pathToAjaxFiles+"now_playing.php",{the_stream:a.playlist_arr[a.origID].radiostream,_:d.now()},function(d){a.playlist_arr[a.origID].title=d;E(a,c,g,e,m,f,l,w,k,r)});E(a,c,g,e,m,f,l,w,k,r);a.isFlashNeeded?""!=a.myFlashObject&&a.myFlashObject.myAS3function(K(a,c,g,e),c.initialVolume):(document.getElementById(a.audioID).src=
 K(a,c,g,e),document.getElementById(a.audioID).load(),c.autoPlay&&m.click());setTimeout(function(){a.radioReaderAjaxInterval=setInterval(function(){d.get(c.pathToAjaxFiles+"now_playing.php",{the_stream:a.playlist_arr[a.origID].radiostream,_:d.now()},function(d){a.playlist_arr[a.origID].title=d;E(a,c,g,e,m,f,l,w,k,r)})},1E3*c.nowPlayingInterval)},1E3*c.nowPlayingInterval)}function T(a,c,g,e,m,f,l,w,k,r){for(var n=!1,t=0;t<a.playlist_arr.length&&!n&&0<a.playlist_arr.length;)a.playlist_arr[t].associatedpageurl==
 a.cur_loc&&(n=!0,a.current_img_no=t,a.origID=d("div[rel='"+a.current_img_no+"']").attr("data-origID"),N(a,c,g,e,m,f,l,w,k,r),C(-1,a,c,g)),t++}function P(a,c,d,e){d.css({background:"url("+e+") #000000","background-repeat":"no-repeat","background-position":"top center","background-size":"cover","border-width":a.imageBorderWidth+"px","border-color":a.imageBorderColor})}function E(a,c,g,e,m,f,l,w,k,r){f.width(a.titleWidth);w.width(a.titleWidth);a.curSongText="";c.showTitle&&null!=a.playlist_arr[a.origID].title&&
 ""!=a.playlist_arr[a.origID].title&&(a.curSongText+="<b>"+c.translateSongTitle+"</b>"+a.playlist_arr[a.origID].title);c.showRadioStation&&null!=a.playlist_arr[a.origID].station&&""!=a.playlist_arr[a.origID].station&&w.html("<b>"+c.translateRadioStation+"</b>"+a.playlist_arr[a.origID].station);var n=a.playlist_arr[a.origID].title.split("-"),t=c.noImageAvailable;n[0]=n[0].trim();if(a.curSongText&&a.prevSongTitle!=a.playlist_arr[a.origID].title)if(l.css({width:"auto"}),a.isStationTitleInsideScrolling=
 !1,a.stationTitleInsideWait=0,l.stop(),l.css({"margin-left":0}),l.html(a.curSongText),clearInterval(a.timeupdateInterval),l.width()>a.titleWidth?a.timeupdateInterval=setInterval(function(){!a.isStationTitleInsideScrolling&&5<=a.stationTitleInsideWait&&l.width()>a.titleWidth?(a.isStationTitleInsideScrolling=!0,a.stationTitleInsideWait=0,l.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),l.css({"margin-left":0}),l.stop().animate({"margin-left":c.playerWidth-
 l.width()+"px"},parseInt(1E4*(l.width()-c.playerWidth)/150,10),"linear",function(){a.isStationTitleInsideScrolling=!1})):!a.isStationTitleInsideScrolling&&l.width()>a.titleWidth&&a.stationTitleInsideWait++},300):l.css({width:"100%"}),a.prevSongTitle=a.playlist_arr[a.origID].title,c.grabLastFmPhoto&&""!=n[0].trim()){var p,u,x,v="";a.the_artist_id="";a.the_wikidata_id="";t=c.noImageAvailable;a.wiki_photo_path=t;clearTimeout(a.musicbrainz_setTimeout);P(c,a,r,t);n[0]=n[0].trim();""!=n[0]&&void 0!=n[0]&&
 (a.musicbrainz_setTimeout=setTimeout(function(){d.get("https://musicbrainz.org/ws/2/artist/?query=artist:"+n[0],{},function(e){a.the_artist_id="";p=n[0];p=p.toLowerCase();p=S(p);d("artist",e).each(function(){x=d("name",this)[0];0<d("name",this).length&&""==a.the_artist_id&&(u=d(x).text(),u=u.toLowerCase(),u=S(u),p.toLowerCase()==u.toLowerCase()&&(a.the_artist_id=d(this).attr("id")))});""==a.the_artist_id&&"ROCK RADIO"!=n[0]&&(a.the_artist_id=d(d("artist",e)[0]).attr("id"));""!=a.the_artist_id&&void 0!=
 a.the_artist_id&&(a.musicbrainz_setTimeout=setTimeout(function(){a.the_wikidata_id="";d.get("https://musicbrainz.org/ws/2/artist/"+a.the_artist_id+"?inc=url-rels",{},function(e){d("relation",e).each(function(){"image"==d(this).attr("type")&&0<d("target",this).length&&(v=d("target",this).text(),v=v.substr(v.indexOf("File:",10)+5,v.length),M(v,c,a,r,t));"wikidata"==d(this).attr("type")&&0<d("target",this).length&&""==v&&(a.the_wikidata_id=d("target",this).text(),a.the_wikidata_id=a.the_wikidata_id.substr(a.the_wikidata_id.indexOf("/Q",
 10)+1,a.the_wikidata_id.length),d.get("https://www.wikidata.org/w/api.php?action=wbgetclaims&entity="+a.the_wikidata_id+"&property=P18&format=xml&origin=*",{},function(e){v=d("datavalue",d("mainsnak",e)).attr("value");M(v,c,a,r,t)}))})})},1500))})},1500))}else P(c,a,r,t)}function C(a,c,g,e){if(c.selectedCateg_total_images>g.numberOfThumbsPerScreen){var m=(c.thumbsHolder_ThumbHeight+1)*(c.selectedCateg_total_images-g.numberOfThumbsPerScreen),f=0;e.stop(!0,!0);d("html, body").off("touchstart touchmove").on("touchstart touchmove",
 function(a){a.preventDefault()});-1==a||c.isCarouselScrolling?!c.isCarouselScrolling&&c.selectedCateg_total_images>g.numberOfThumbsPerScreen&&(c.isCarouselScrolling=!0,f=-1*parseInt((c.thumbsHolder_ThumbHeight+1)*c.current_img_no,10),Math.abs(f)>m&&(f=-1*m),c.selectedCateg_total_images>g.numberOfThumbsPerScreen&&g.showPlaylist&&c.audio5_html5_sliderVertical.slider("value",100+parseInt(100*f/m)),e.animate({top:f+"px"},500,"easeOutCubic",function(){c.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",
 function(a){})})):(c.isCarouselScrolling=!0,f=2>=a?-1*m:parseInt(m*(a-100)/100,10),0<f&&(f=0),e.animate({top:f+"px"},600,"easeOutQuad",function(){c.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})}))}}function W(a,c,g,e,m,f,l,w,k,r,n,t,p,u,x,v){e.stop(!0,!0);a.isCarouselScrolling=!1;e.stop().animate({left:-1*f.width()+"px"},100,"easeOutQuad",function(){e.html("");for(var q=0;q<a.category_arr.length;q++)a.thumbsHolder_Thumb=d('<div class="thumbsHolder_ThumbOFF" rel="'+
 q+'"><div class="padding">'+a.category_arr[q]+"</div></div>"),e.append(a.thumbsHolder_Thumb),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_Thumb.height()+1)*q+"px",background:c.categoryRecordBgOffColor,"border-bottom-color":c.categoryRecordBottomBorderOffColor,color:c.categoryRecordTextOffColor}),a.category_arr[q]==a.selectedCateg&&(a.current_img_no=q,a.thumbsHolder_Thumb.css({background:c.categoryRecordBgOnColor,"border-bottom-color":c.categoryRecordBottomBorderOnColor,color:c.categoryRecordTextOnColor}));
 a.selectedCateg_total_images=a.numberOfCategories;a.categsAreListed=!0;q=0;c.showCategories&&(q+=c.selectedCategMarginBottom);c.showSearchArea&&(q+=c.selectedCategMarginBottom);m.height(2*c.playlistPadding+(a.thumbsHolder_Thumb.height()+1)*c.numberOfThumbsPerScreen+l.height()+k.height()+q);f.height((a.thumbsHolder_Thumb.height()+1)*c.numberOfThumbsPerScreen);r.css({padding:c.playlistPadding+"px"});a.thumbsHolder_Thumbs=d(".thumbsHolder_ThumbOFF",g);if(a.numberOfCategories>c.numberOfThumbsPerScreen&&
 c.showPlaylist){c.isPlaylistSliderInitialized&&a.audio5_html5_sliderVertical.slider("destroy");a.audio5_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(d,g){C(g.value,a,c,e)}});c.isPlaylistSliderInitialized=!0;var h=0;c.showSearchArea&&(h+=c.selectedCategMarginBottom);a.audio5_html5_sliderVertical.css({display:"inline",position:"absolute",height:m.height()-16-l.height()-q-k.height()-2*c.playlistPadding+"px",left:g.width()+2*c.playerPadding-
 a.audio5_html5_sliderVertical.width()-c.playlistPadding+"px",bottom:a.audioPlayerHeight+c.playlistTopPos+c.playlistPadding+k.height()+h+16+"px"});c.showPlaylistOnInit||a.audio5_html5_sliderVertical.css({opacity:0,display:"none"});c.showPlaylistOnInit=!0;d(".thumbsHolder_ThumbOFF",g).css({width:g.width()+2*c.playerPadding-a.audio5_html5_sliderVertical.width()-2*c.playlistPadding-3+"px"})}else c.isPlaylistSliderInitialized&&(a.audio5_html5_sliderVertical.slider("destroy"),c.isPlaylistSliderInitialized=
 !1),d(".thumbsHolder_ThumbOFF",g).css({width:g.width()+2*c.playerPadding-2*c.playlistPadding+"px"});a.thumbsHolder_Thumbs.on("click",function(){var h=d(this).attr("rel");a.selectedCateg=a.category_arr[h];D(c,"cookie_firstCateg",a.selectedCateg);w.html(a.selectedCateg);Q(a,c,g,e,m,f,l,k,r,n,t,p,u,x,v)});a.thumbsHolder_Thumbs.on("mouseover",function(){d(this).css({background:c.categoryRecordBgOnColor,"border-bottom-color":c.categoryRecordBottomBorderOnColor,color:c.categoryRecordTextOnColor})});a.thumbsHolder_Thumbs.on("mouseout",
 function(){var e=d(this),g=e.attr("rel");a.current_img_no!=g&&e.css({background:c.categoryRecordBgOffColor,"border-bottom-color":c.categoryRecordBottomBorderOffColor,color:c.categoryRecordTextOffColor})});f.mousewheel(function(d,g,b,f){d.preventDefault();d=a.audio5_html5_sliderVertical.slider("value");if(1<parseInt(d)&&-1==parseInt(g)||100>parseInt(d)&&1==parseInt(g))d+=g,a.audio5_html5_sliderVertical.slider("value",d),C(d,a,c,e)});e.css({top:"0px"});e.stop().animate({left:"0px"},400,"easeOutQuad",
 function(){})})}function Q(a,c,g,e,m,f,l,w,k,r,n,t,p,u,x){e.stop(!0,!0);a.isCarouselScrolling=!1;var v="",q=!1,h=500;a.is_very_first&&(h=1);""!=a.search_val&&(h=1);e.stop().animate({left:-1*f.width()+"px"},h,"easeOutQuad",function(){e.html("");for(var h=a.selectedCateg_total_images=0;h<a.playlist_arr.length;h++)q=!1,""!=a.search_val?(v=a.playlist_arr[h].station.toLowerCase(),-1!=v.indexOf(a.search_val)&&(q=!0)):-1!=a.playlist_arr[h].category.indexOf(a.selectedCateg+";")&&(q=!0),q&&(a.selectedCateg_total_images++,
 a.thumbsHolder_Thumb=d('<div class="thumbsHolder_ThumbOFF" rel="'+(a.selectedCateg_total_images-1)+'" data-origID="'+h+'"><div class="padding">'+(c.showPlaylistNumber?a.selectedCateg_total_images+". ":"")+a.playlist_arr[h].station+"</div></div>"),e.append(a.thumbsHolder_Thumb),0==a.thumbsHolder_ThumbHeight&&(a.thumbsHolder_ThumbHeight=a.thumbsHolder_Thumb.height()),a.thumbsHolder_Thumb.css({top:(a.thumbsHolder_ThumbHeight+1)*a.selectedCateg_total_images+"px",background:c.playlistRecordBgOffColor,
 "border-bottom-color":c.playlistRecordBottomBorderOffColor,color:c.playlistRecordTextOffColor}),a.current_img_no=0,a.origID==d("div[rel='"+(a.selectedCateg_total_images-1)+"']").attr("data-origID")&&a.thumbsHolder_Thumb.css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor}));a.categsAreListed=!1;h=0;c.showCategories&&(h+=c.selectedCategMarginBottom);c.showSearchArea&&(h+=c.selectedCategMarginBottom);m.height(2*c.playlistPadding+
 (a.thumbsHolder_ThumbHeight+1)*c.numberOfThumbsPerScreen+l.height()+w.height()+h);f.height((a.thumbsHolder_ThumbHeight+1)*c.numberOfThumbsPerScreen);k.css({padding:c.playlistPadding+"px"});a.thumbsHolder_Thumbs=d(".thumbsHolder_ThumbOFF",g);if(a.selectedCateg_total_images>c.numberOfThumbsPerScreen&&c.showPlaylist){c.isPlaylistSliderInitialized&&a.audio5_html5_sliderVertical.slider("destroy");a.audio5_html5_sliderVertical.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(b,
 d){C(d.value,a,c,e)}});c.isPlaylistSliderInitialized=!0;var z=0;c.showSearchArea&&(z+=c.selectedCategMarginBottom);a.audio5_html5_sliderVertical.css({display:"inline",position:"absolute",height:m.height()-16-l.height()-h-w.height()-2*c.playlistPadding+"px",left:g.width()+2*c.playerPadding-a.audio5_html5_sliderVertical.width()-c.playlistPadding+"px",bottom:a.audioPlayerHeight+c.playlistTopPos+c.playlistPadding+w.height()+z+16+"px"});c.showPlaylistOnInit||a.audio5_html5_sliderVertical.css({opacity:0,
 display:"none"});c.showPlaylistOnInit=!0;d(".thumbsHolder_ThumbOFF",g).css({width:g.width()+2*c.playerPadding-a.audio5_html5_sliderVertical.width()-2*c.playlistPadding-3+"px"})}else c.isPlaylistSliderInitialized&&(a.audio5_html5_sliderVertical.slider("destroy"),c.isPlaylistSliderInitialized=!1),d(".thumbsHolder_ThumbOFF",g).css({width:g.width()+2*c.playerPadding-2*c.playlistPadding+"px"});a.thumbsHolder_Thumbs.on("click",function(){c.autoPlay=!0;var b=d(this).attr("rel");a.thumbsHolder_Thumbs.css({background:c.playlistRecordBgOffColor,
 "border-bottom-color":c.playlistRecordBottomBorderOffColor,color:c.playlistRecordTextOffColor});a.current_img_no=b;a.origID=d("div[rel='"+a.current_img_no+"']").attr("data-origID");D(c,"cookie_current_img_no",a.current_img_no);D(c,"cookie_origID",a.origID);r.addClass("AudioPause");N(a,c,e,g,r,n,t,p,u,x);C(-1,a,c,e)});a.thumbsHolder_Thumbs.on("mouseover",function(){d(this).css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor})});
 a.thumbsHolder_Thumbs.on("mouseout",function(){var b=d(this),e=b.attr("rel");a.origID!=d("div[rel='"+e+"']").attr("data-origID")&&b.css({background:c.playlistRecordBgOffColor,"border-bottom-color":c.playlistRecordBottomBorderOffColor,color:c.playlistRecordTextOffColor})});f.mousewheel(function(b,d,g,f){b.preventDefault();b=a.audio5_html5_sliderVertical.slider("value");if(1<parseInt(b)&&-1==parseInt(d)||100>parseInt(b)&&1==parseInt(d))b+=d,a.audio5_html5_sliderVertical.slider("value",b),C(b,a,c,e)});
 e.css({top:"0px"});e.stop().animate({left:"0px"},400,"easeOutQuad",function(){});a.cur_loc=window.location.href;T(a,c,e,g,r,n,t,p,u,x);a.cur_intv=setInterval(function(){a.cur_loc!=window.location.href&&0<a.playlist_arr.length&&(a.cur_loc=window.location.href,T(a,c,e,g,r,n,t,p,u,x))},5E3)})}function D(a,c,d,e){null==e&&(e=86400);a="; max-age="+e;document.cookie=encodeURI(c)+"="+encodeURI(d)+a+"; path=/"}function G(a,c){var d,e=document.cookie.split(";");for(d=0;d<e.length;d++){var m=e[d].substr(0,
 e[d].indexOf("="));var f=e[d].substr(e[d].indexOf("=")+1);m=m.replace(/^\s+|\s+$/g,"");if(m==c)return unescape(f)}}function U(a,c,g){"next"==g?a.current_img_no==a.selectedCateg_total_images-1?a.current_img_no=0:a.current_img_no++:0>a.current_img_no-1?a.current_img_no=a.selectedCateg_total_images-1:a.current_img_no--;a.origID=d("div[rel='"+a.current_img_no+"']").attr("data-origID")}function X(){d("audio").each(function(){d(".AudioPlay").removeClass("AudioPause");d(this)[0].pause()})}function V(){var a=
 -1;if("Microsoft Internet Explorer"==navigator.appName){var c=navigator.userAgent,d=/MSIE ([0-9]{1,}[.0-9]{0,})/;null!=d.exec(c)&&(a=parseFloat(RegExp.$1))}else"Netscape"==navigator.appName&&(c=navigator.userAgent,d=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/,null!=d.exec(c)&&(a=parseFloat(RegExp.$1)));return parseInt(a,10)}function Y(a){var c=!1;document.getElementById(a.audioID).canPlayType&&"no"!=document.getElementById(a.audioID).canPlayType("audio/mpeg")&&""!=document.getElementById(a.audioID).canPlayType("audio/mpeg")||
 (c=!0);return c}var z=navigator.userAgent.toLowerCase();d.fn.audio5_html5=function(a){a=d.extend({},d.fn.audio5_html5.defaults,a);V();return this.each(function(){var c=d(this),g=d('<div class="FrameBehindPlayerText"></div><div class="FrameBehindPlayer"></div> <div class="headphone"></div> <div class="ximage"></div> <div class="AudioControls"> <a class="AudioFacebook" title="Facebook"></a><a class="AudioTwitter" title="Twitter"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioPrev" title="Previous"></a><a class="AudioNext" title="Next"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div>   </div>   <div class="songTitle"><div class="songTitleInside"></div></div>  <div class="radioStation"></div>     <div class="thumbsHolderWrapper"><div class="playlistPadding"><div class="selectedCategDiv"><div class="innerSelectedCategDiv">reading the categories...</div></div> <div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div><div class="searchDiv"><input class="search_term" type="text" value="search..." /></div></div></div>  <div class="slider-vertical"></div>'),
 e=c.parent(".audio5_html5");e.addClass(a.skin);e.append(g);var m=d(".FrameBehindPlayerText",e),f=d(".FrameBehindPlayer",e);d(".AudioControls",e);var l=d(".AudioFacebook",e),w=d(".AudioTwitter",e),k=d(".AudioPlay",e),r=d(".AudioPrev",e),n=d(".AudioNext",e),t=d(".AudioShowHidePlaylist",e),p=d(".VolumeButton",e),u=d(".VolumeSlider",e),x=d(".songTitle",e),v=d(".songTitleInside",e),q=d(".radioStation",e),h=d(".ximage",e),L=d(".headphone",e),E=V();if(-1!=z.indexOf("ipad")||-1!=z.indexOf("iphone")||-1!=
 z.indexOf("ipod")||-1!=z.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoHidePlayButton=!1,k.css("display","block"),a.autoPlay=!1;e.css({background:"transparent",padding:a.playerPadding+"px"});f.css({background:a.frameBehindPlayerColor});m.css({background:a.beneathTitleBackgroundColor_VisiblePlaylist,opacity:a.beneathTitleBackgroundOpacity_VisiblePlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor});jQuery(".audio5_html5_arrow_down").css({"border-top-color":a.minButtonColor});
 jQuery(".audio5_html5_min").on("click",function(){var c=400;"true"==b.cookie_isMinified&&(c=0);jQuery(this).hasClass("audio5_html5_arrow_down")?(jQuery(this).removeClass("audio5_html5_arrow_down"),jQuery(this).addClass("audio5_html5_arrow_up"),jQuery(".audio5_html5_arrow_up").css({"border-bottom-color":a.minButtonColor}),e.slideToggle(c,function(){}),b.cookie_isMinified=!0):(jQuery(this).removeClass("audio5_html5_arrow_up"),jQuery(this).addClass("audio5_html5_arrow_down"),e.slideToggle(c,function(){}),
 b.cookie_isMinified=!1);D(a,"cookie_isMinified",b.cookie_isMinified)});var b={current_img_no:0,origID:0,is_very_first:!0,total_images:0,selectedCateg_total_images:0,numberOfCategories:0,is_changeSrc:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",isCarouselScrolling:!1,isStationTitleInsideScrolling:!1,curSongText:"",prevSongTitle:"",stationTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,category_arr:"",selectedCateg:"",categsAreListed:!1,thumbsHolder_Thumb:d('<div class="thumbsHolder_ThumbOFF" rel="0"><div class="padding">test</div></div>'),
 thumbsHolder_ThumbHeight:0,thumbsHolder_Thumbs:"",search_val:"",constantDistance:5,playerTopMargin:23,titleWidth:0,radioStationTopPos:0,radioStationLeftPos:0,titleTopPos:0,titleLeftPos:0,frameBehindPlayerTopPos:0,frameBehindPlayerLeftPos:0,imageTopPos:0,imageLeftPos:0,playTopPos:0,playLeftPos:0,previousTopPos:0,previousLeftPos:0,nextTopPos:0,nextLeftPos:0,headphoneTopPos:0,headphoneLeftPos:0,volumeTopPos:0,volumeLeftPos:0,volumesliderTopPos:0,volumesliderLeftPos:0,showhideplaylistTopPos:0,showhideplaylistLeftPos:0,
 smallButtonDistance:0,facebookTopPos:0,facebookLeftPos:0,twitterTopPos:0,twitterLeftPos:0,numberOfButtonsRightSide:3,origParentFloat:"",origParentPaddingTop:"",origParentPaddingRight:"",origParentPaddingBottom:"",origParentPaddingLeft:"",windowWidth:0,audioID:"",audioObj:"",radioReaderAjaxInterval:"",totalRadioStationsNo:0,ajaxReturnedRadioStationsNo:0,lastfm:"",isFlashNeeded:!0,myFlashObject:"",rndNum:0,prevVolumeVal:1,cur_loc:"",cur_intv:"",cookie_isMinified:!1,cookie_current_img_no:0,cookie_origID:0,
 cookie_initialVolume:0,cookie_muteVolume:0,cookie_autoPlay:!1,cookie_firstCateg:"",the_artist_id:"",the_wikidata_id:"",musicbrainz_setTimeout:"",wiki_photo_path:a.noImageAvailable};b.audioID=c.attr("id");35>a.nowPlayingInterval&&(a.nowPlayingInterval=40);b.isFlashNeeded=Y(b);-1!=E&&(b.isFlashNeeded=!0);b.cookie_current_img_no=G(a,"cookie_current_img_no");b.cookie_origID=G(a,"cookie_origID");void 0!=b.cookie_current_img_no&&(b.current_img_no=b.cookie_current_img_no,void 0!=b.cookie_origID&&(b.origID=
 b.cookie_origID));b.cookie_autoPlay=G(a,"cookie_autoPlay");void 0!=b.cookie_autoPlay&&(a.autoPlay="true"==b.cookie_autoPlay?!0:!1);if(-1!=z.indexOf("ipad")||-1!=z.indexOf("iphone")||-1!=z.indexOf("ipod")||-1!=z.indexOf("webos")||-1!=navigator.userAgent.indexOf("Android"))a.autoPlay=!1;"true"!=b.cookie_autoPlay&&-1==(-1==navigator.userAgent.indexOf("Opera")&&navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&(a.autoPlay=!1),-1<navigator.userAgent.indexOf("Firefox")&&
 (a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));b.cookie_initialVolume=G(a,"cookie_initialVolume");b.cookie_initialVolume&&(a.initialVolume=b.cookie_initialVolume);b.cookie_muteVolume=G(a,"cookie_muteVolume");1<=b.cookie_muteVolume&&setTimeout(function(){p.click()},300);b.cookie_firstCateg=G(a,"cookie_firstCateg");void 0!=b.cookie_firstCateg&&(a.firstCateg=b.cookie_firstCateg);a.showFacebookBut||
 --b.numberOfButtonsRightSide;a.showTwitterBut||--b.numberOfButtonsRightSide;a.showPlaylistBut||--b.numberOfButtonsRightSide;a.showPlaylistBut||t.css({display:"none",padding:0,margin:0});a.showHeadphone||(b.playerTopMargin=0);e.width(a.playerWidth);a.origWidth=a.playerWidth;f.css({top:parseInt((h.height()+2*a.imageBorderWidth-f.height())/2,10)+b.playerTopMargin+"px",left:"0px"});b.frameBehindPlayerTopPos=parseInt(f.css("top").substring(0,f.css("top").length-2),10);b.frameBehindPlayerLeftPos=parseInt(f.css("left").substring(0,
 f.css("left").length-2),10);m.css({top:b.frameBehindPlayerTopPos+f.height()+"px",left:"0px"});h.css({top:b.playerTopMargin+"px",left:parseInt((e.width()-(h.width()+2*a.imageBorderWidth))/2,10)+"px"});P(a,b,h,a.noImageAvailable);b.imageTopPos=parseInt(h.css("top").substring(0,h.css("top").length-2),10);b.imageLeftPos=parseInt(h.css("left").substring(0,h.css("left").length-2),10);a.autoHidePlayButton&&(d("*").on("click",function(){k.css({display:"none"})}),h.on("mouseover",function(){b.playTopPos=b.frameBehindPlayerTopPos+
 parseInt((f.height()-k.height())/2,10);b.playLeftPos=parseInt((f.width()-k.width())/2,10);k.css({top:b.playTopPos+"px",left:b.playLeftPos+"px"});k.css({display:"block"})}),h.on("mouseout",function(){k.css({display:"none"})}),k.on("mouseover",function(){k.css({display:"block"})}));h.on("click",function(){k.click();k.css({display:"block"})});b.playTopPos=b.frameBehindPlayerTopPos+parseInt((f.height()-k.height())/2,10);b.playLeftPos=parseInt((f.width()-k.width())/2,10);k.css({top:b.playTopPos+"px",left:b.playLeftPos+
 "px"});a.autoHidePlayButton&&setTimeout(function(){k.fadeOut(1500,function(){})},2E3);a.showNextPrevBut||(r.css({display:"none",width:0,padding:0,margin:0}),n.css({display:"none",width:0,padding:0,margin:0}));b.previousTopPos=b.playTopPos+parseInt((k.height()-r.height())/2,10);b.previousLeftPos=b.imageLeftPos-r.width()-a.nextPrevAdditionalPadding;r.css({top:b.previousTopPos+"px",left:b.previousLeftPos+"px"});b.nextTopPos=b.previousTopPos;b.nextLeftPos=b.imageLeftPos+(h.width()+2*a.imageBorderWidth)+
 a.nextPrevAdditionalPadding;n.css({top:b.nextTopPos+"px",left:b.nextLeftPos+"px"});a.showHeadphone?(b.headphoneTopPos=0,b.headphoneLeftPos=parseInt(b.imageLeftPos+(h.width()+2*a.imageBorderWidth-L.width())/2,10),L.css({left:b.headphoneLeftPos+"px",top:b.headphoneTopPos+"px"})):L.css({display:"none"});a.showVolume?(b.volumeTopPos=b.nextTopPos+Math.floor((n.height()-p.height())/2),b.volumeLeftPos=parseInt((b.previousLeftPos-(p.width()+u.width()+b.constantDistance))/2,10),p.css({top:b.volumeTopPos+"px",
 left:b.volumeLeftPos+"px"}),b.volumesliderTopPos=b.volumeTopPos+Math.floor((p.height()-u.height())/2),b.volumesliderLeftPos=b.volumeLeftPos+p.width()+b.constantDistance,u.css({top:b.volumesliderTopPos+"px",left:b.volumesliderLeftPos+"px"})):(p.css({display:"none",width:0,padding:0,margin:0}),u.css({display:"none",width:0,padding:0,margin:0}));b.audioPlayerHeight=h.height()+2*a.imageBorderWidth+b.constantDistance+q.height()+b.constantDistance+x.height()+2*b.constantDistance+b.playerTopMargin;a.showRadioStation||
 a.showTitle?a.showTitle||(b.audioPlayerHeight-=21):b.audioPlayerHeight-=42;e.height(b.audioPlayerHeight);b.smallButtonDistance=parseInt((a.playerWidth-b.nextLeftPos-n.width()-b.numberOfButtonsRightSide*t.width())/(b.numberOfButtonsRightSide+1),10);b.facebookTopPos=b.nextTopPos+Math.floor((n.height()-l.height())/2);b.facebookLeftPos=b.nextLeftPos+n.width()+b.smallButtonDistance;l.css({top:b.facebookTopPos+"px",left:b.facebookLeftPos+"px"});a.showFacebookBut?(window.fbAsyncInit=function(){FB.init({appId:a.facebookAppID,
 version:"v3.2",status:!0,cookie:!0,xfbml:!0})},function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.com/en_US/sdk.js",d.parentNode.insertBefore(a,d))}(document,"script","facebook-jssdk")):(l.css({display:"none",width:0,padding:0,margin:0}),b.facebookLeftPos=b.nextLeftPos+n.width());l.on("click",function(){FB.ui({method:"share_open_graph",action_type:"og.likes",action_properties:JSON.stringify({object:{"og:url":document.URL,
 "og:title":a.facebookShareTitle,"og:description":a.facebookShareDescription}})},function(a){})});b.twitterTopPos=b.nextTopPos+Math.floor((n.height()-l.height())/2);b.twitterLeftPos=b.facebookLeftPos+l.width()+b.smallButtonDistance;w.css({top:b.twitterTopPos+"px",left:b.twitterLeftPos+"px"});a.showTwitterBut||(w.css({display:"none",width:0,padding:0,margin:0}),b.twitterLeftPos=b.facebookLeftPos+l.width());w.on("click",function(){var a=b.playlist_arr[b.origID].station.replace("%","percent");a=a.replace("&",
 " and ");window.open("https://twitter.com/intent/tweet?url="+document.URL+"&text="+a,"Twitter","status = 1, left = 430, top = 270, height = 550, width = 420, resizable = 0")});b.showhideplaylistTopPos=b.nextTopPos+Math.floor((n.height()-t.height())/2);b.showhideplaylistLeftPos=b.volumeLeftPos-b.smallButtonDistance;t.css({top:b.showhideplaylistTopPos+"px",left:b.showhideplaylistLeftPos+"px"});x.css({color:a.songTitleColor});q.css({color:a.radioStationColor});b.titleWidth=a.playerWidth-2*a.playlistPadding;
 b.radioStationTopPos=b.imageTopPos+(h.width()+2*a.imageBorderWidth)+2*b.constantDistance;b.radioStationLeftPos=a.playlistPadding;b.titleTopPos=b.imageTopPos+(h.width()+2*a.imageBorderWidth)+2*b.constantDistance+q.height()+b.constantDistance;b.titleLeftPos=a.playlistPadding;q.css({top:b.radioStationTopPos+"px",left:b.radioStationLeftPos+"px"});x.css({top:b.titleTopPos+"px",left:b.titleLeftPos+"px"});m.css({top:b.frameBehindPlayerTopPos+f.height()+"px",left:"0px",height:parseInt(e.height()/2,10)+f.height()+
 "px"});var y=d(".thumbsHolderWrapper",e),O=d(".playlistPadding",e),F=d(".thumbsHolderVisibleWrapper",e),A=d(".thumbsHolder",e);b.audio5_html5_sliderVertical=d(".slider-vertical",e);var B=d(".selectedCategDiv",e),H=d(".innerSelectedCategDiv",e),I=d(".searchDiv",e),J=d(".search_term",e);O.css({padding:a.playlistPadding+"px"});F.append('<div class="readingData">'+a.translateReadingData+"</div>");a.showPlaylist||y.css({opacity:0});a.showPlaylistOnInit||(y.css({opacity:0,visibility:"hidden","margin-top":"-20px"}),
 m.css({background:a.beneathTitleBackgroundColor_HiddenPlaylist,opacity:a.beneathTitleBackgroundOpacity_HiddenPlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor}));B.css({"background-color":a.selectedCategBg,"background-position":"10px 50%","margin-bottom":a.selectedCategMarginBottom+"px"});H.css({color:a.selectedCategOffColor,"background-position":a.playerWidth-2*a.playlistPadding-20+"px 50%"});a.showCategories||B.css({display:"none",width:0,
 height:0,padding:0,margin:0});I.css({"background-color":a.searchAreaBg,"margin-top":a.selectedCategMarginBottom+"px"});J.val(a.searchInputText);J.css({width:parseInt(a.playerWidth-2*a.playlistPadding-37,10)+"px","background-color":a.searchInputBg,"border-color":a.searchInputBorderColor,color:a.searchInputTextColor});a.showSearchArea||I.css({display:"none",width:0,height:0,padding:0,margin:0});y.css({width:e.width()+2*a.playerPadding+"px",bottom:-1*b.audioPlayerHeight+"px",left:"0px",background:a.playlistBgColor});
 F.width(e.width());b.playlist_arr=[];b.category_arr=[];d(".xaudioplaylist",e).children().each(function(){currentElement=d(this);b.total_images++;b.playlist_arr[b.total_images-1]=[];b.playlist_arr[b.total_images-1].title="";b.playlist_arr[b.total_images-1].station="";b.playlist_arr[b.total_images-1].image="";b.playlist_arr[b.total_images-1].category="";b.playlist_arr[b.total_images-1].radiostream="";b.playlist_arr[b.total_images-1].associatedpageurl="";null!=currentElement.find(".xtitle").html()&&
 (b.playlist_arr[b.total_images-1].title=currentElement.find(".xtitle").html());null!=currentElement.find(".xstation").html()&&(b.playlist_arr[b.total_images-1].station=currentElement.find(".xstation").html());null!=currentElement.find(".ximage").html()&&(b.playlist_arr[b.total_images-1].image=currentElement.find(".ximage").html());if(null!=currentElement.find(".xcategory").html()&&(b.playlist_arr[b.total_images-1].category=a.translateAllRadioStations+";"+currentElement.find(".xcategory").html()+";",
 !a.grabStreamnameAndGenre)){var f=[];f=b.playlist_arr[b.total_images-1].category.split(";");for(var g=0;g<f.length;g++)f[g]=f[g].trim(),-1===b.category_arr.indexOf(f[g])&&""!=f[g]&&b.category_arr.push(f[g])}null!=currentElement.find(".xassociatedpageurl").html()&&(b.playlist_arr[b.total_images-1].associatedpageurl=currentElement.find(".xassociatedpageurl").html());null!=currentElement.find(".xradiostream").html()&&(b.playlist_arr[b.total_images-1].radiostream=currentElement.find(".xradiostream").html(),
 -1==b.playlist_arr[b.total_images-1].radiostream.indexOf("/",9)&&(b.playlist_arr[b.total_images-1].radiostream+="/;"),"/"==b.playlist_arr[b.total_images-1].radiostream.charAt(b.playlist_arr[b.total_images-1].radiostream.length-1)&&(b.playlist_arr[b.total_images-1].radiostream+=";"),b.totalRadioStationsNo++,a.grabStreamnameAndGenre&&d.get(a.pathToAjaxFiles+"streamandgenre.php",{the_stream:b.playlist_arr[b.total_images-1].radiostream,cur_i:b.total_images-1,translateAllRadioStations:a.translateAllRadioStations,
 _:d.now()},function(f){b.ajaxReturnedRadioStationsNo++;f=f.split("#----#");2<=f.length&&""==b.playlist_arr[f[0]].station&&(b.playlist_arr[f[0]].station=f[1]);3<=f.length&&""==b.playlist_arr[f[0]].category&&(b.playlist_arr[f[0]].category=f[2]+";");""==b.playlist_arr[f[0]].category&&(b.playlist_arr[f[0]].category=a.translateAllRadioStations);f=b.playlist_arr[f[0]].category.split(";");for(var g=0;g<f.length;g++)f[g]=f[g].trim(),-1===b.category_arr.indexOf(f[g])&&""!=f[g]&&b.category_arr.push(f[g]);b.ajaxReturnedRadioStationsNo==
 b.totalRadioStationsNo&&(b.numberOfCategories=b.category_arr.length,b.selectedCateg=a.firstCateg,b.category_arr.sort(),""==a.firstCateg&&-1===b.category_arr.indexOf(a.firstCateg)&&(b.selectedCateg=b.category_arr[0]),H.html(b.selectedCateg),d(".readingData").remove(),Q(b,a,e,A,y,F,B,I,O,k,x,v,q,c,h))}))});a.grabStreamnameAndGenre||(b.numberOfCategories=b.category_arr.length,b.selectedCateg=a.firstCateg,b.category_arr.sort(),""==a.firstCateg&&-1===b.category_arr.indexOf(a.firstCateg)&&(b.selectedCateg=
 b.category_arr[0]),H.html(b.selectedCateg),d(".readingData").remove(),Q(b,a,e,A,y,F,B,I,O,k,x,v,q,c,h));B.on("click",function(){b.search_val="";J.val(a.searchInputText);W(b,a,e,A,y,F,B,H,I,O,k,x,v,q,c,h)});B.on("mouseover",function(){H.css({color:a.selectedCategOnColor})});B.on("mouseout",function(){H.css({color:a.selectedCategOffColor})});u.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(c,d){a.initialVolume=d.value;b.isFlashNeeded?b.myFlashObject.myAS3function(K(b,
 a,A,e),a.initialVolume):(document.getElementById(b.audioID).volume=d.value,D(a,"cookie_initialVolume",d.value))},stop:function(a,b){}});document.getElementById(b.audioID).volume=a.initialVolume;u.css({background:a.volumeOffColor});d(".ui-slider-range",u).css({background:a.volumeOnColor});k.on("click",function(){var c=b.isFlashNeeded?!k.hasClass("AudioPause"):document.getElementById(b.audioID).paused;X();0==c?(b.isFlashNeeded?b.myFlashObject.myAS3function("_pause_radio_stream_",a.initialVolume):document.getElementById(b.audioID).pause(),
 k.removeClass("AudioPause"),D(a,"cookie_autoPlay",!1)):(b.isFlashNeeded?b.myFlashObject.myAS3function("_play_radio_stream_",a.initialVolume):(document.getElementById(b.audioID).src=K(b,a,A,e),document.getElementById(b.audioID).load(),document.getElementById(b.audioID).play()),k.addClass("AudioPause"),D(a,"cookie_autoPlay",!0))});n.on("click",function(){!b.categsAreListed&&b.is_very_first&&(k.addClass("AudioPause"),a.autoPlay=!0,b.thumbsHolder_Thumbs.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,
 color:a.playlistRecordTextOffColor}),U(b,a,"next"),N(b,a,A,e,k,x,v,q,c,h),C(-1,b,a,A))});r.on("click",function(){!b.categsAreListed&&b.is_very_first&&(k.addClass("AudioPause"),a.autoPlay=!0,b.thumbsHolder_Thumbs.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor}),U(b,a,"previous"),N(b,a,A,e,k,x,v,q,c,h),C(-1,b,a,A))});t.on("click",function(){y.css({visibility:"visible"});if(0>y.css("bottom").substring(0,y.css("bottom").length-
 2)){var c=1,d="block";B.height();I.height();aux_bottom=b.audioPlayerHeight+a.playlistTopPos;y.css({display:d});m.css({background:a.beneathTitleBackgroundColor_VisiblePlaylist,opacity:a.beneathTitleBackgroundOpacity_VisiblePlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor})}else c=0,d="none",aux_bottom=-1*b.audioPlayerHeight,b.selectedCateg_total_images>a.numberOfThumbsPerScreen&&b.audio5_html5_sliderVertical.css({opacity:0,display:"none"}),
 m.css({background:a.beneathTitleBackgroundColor_HiddenPlaylist,opacity:a.beneathTitleBackgroundOpacity_HiddenPlaylist/100,"border-bottom":a.beneathTitleBackgroundBorderWidth+"px solid "+a.beneathTitleBackgroundBorderColor});y.css({opacity:1,display:"block"});y.animate({opacity:c,bottom:aux_bottom+"px"},500,"swing",function(){y.css({display:d});b.selectedCateg_total_images>a.numberOfThumbsPerScreen&&b.audio5_html5_sliderVertical.css({opacity:1,display:d})})});p.on("click",function(){document.getElementById(b.audioID).muted?
 (document.getElementById(b.audioID).muted=!1,p.removeClass("VolumeButtonMuted"),D(a,"cookie_muteVolume",0),b.isFlashNeeded&&(a.initialVolume=b.prevVolumeVal,b.myFlashObject.myAS3function(K(b,a,A,e),a.initialVolume))):(document.getElementById(b.audioID).muted=!0,p.addClass("VolumeButtonMuted"),D(a,"cookie_muteVolume",1),b.isFlashNeeded&&(b.prevVolumeVal=a.initialVolume,a.initialVolume=0,b.myFlashObject.myAS3function(K(b,a,A,e),a.initialVolume)))});A.swipe({swipeStatus:function(c,e,f,g,h,k){"up"!=f&&
 "down"!=f||0==g||(currentScrollVal=b.audio5_html5_sliderVertical.slider("value"),currentScrollVal="up"==f?currentScrollVal-1.5:currentScrollVal+1.5,b.audio5_html5_sliderVertical.slider("value",currentScrollVal),d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()}),C(currentScrollVal,b,a,A))},threshold:100,maxTimeThreshold:500,fingers:"all"});J.on("click",function(){d(this).val("")});J.on("input",function(){b.search_val=J.val().toLowerCase();Q(b,a,e,
 A,y,F,B,I,O,k,x,v,q,c,h)});b.cookie_isMinified=G(a,"cookie_isMinified");void 0==b.cookie_isMinified&&(b.cookie_isMinified=!1);"true"==b.cookie_isMinified&&jQuery(".audio5_html5_min").click();b.isFlashNeeded&&(b.rndNum=parseInt(998999*Math.random()+1E3),e.append("<div id='swfHolder"+b.rndNum+"'></div>"),swfobject.addDomLoadEvent(function(){b.myFlashObject=swfobject.createSWF({data:a.pathToAjaxFiles+"flash_player.swf",width:"0",height:"0"},{flashvars:"streamUrl="+b.playlist_arr[b.origID].radiostream+
 "&autoPlay="+a.autoPlay+"&initialVolume="+a.initialVolume},"swfHolder"+b.rndNum)}),a.autoPlay&&k.addClass("AudioPause"));N(b,a,A,e,k,x,v,q,c,h);-1==z.indexOf("ipad")&&-1==z.indexOf("iphone")&&-1==z.indexOf("ipod")&&-1==z.indexOf("webos")||k.removeClass("AudioPause");var M=function(){b.prevSongTitle="";""==b.origParentFloat&&(b.origParentFloat=e.parent().css("float"),b.origParentPaddingTop=e.parent().css("padding-top"),b.origParentPaddingRight=e.parent().css("padding-right"),b.origParentPaddingBottom=
 e.parent().css("padding-bottom"),b.origParentPaddingLeft=e.parent().css("padding-left"));a.playerWidth!=a.origWidth||a.playerWidth>d(window).width()?e.parent().css({"float":"none","padding-top":0,"padding-right":0,"padding-bottom":0,"padding-left":0}):e.parent().css({"float":b.origParentFloat,"padding-top":b.origParentPaddingTop,"padding-right":b.origParentPaddingRight,"padding-bottom":b.origParentPaddingBottom,"padding-left":b.origParentPaddingLeft});var c=e.parent().width(),g=b.numberOfButtonsRightSide;
 e.width()!=c&&(a.playerWidth=a.origWidth>c?c:a.origWidth,e.width()!=a.playerWidth&&(e.width(a.playerWidth),b.titleWidth=a.playerWidth-2*a.playlistPadding,x.width(b.titleWidth),q.width(b.titleWidth),h.css({top:b.playerTopMargin+"px",left:parseInt((e.width()-(h.width()+2*a.imageBorderWidth))/2,10)+"px"}),b.imageLeftPos=parseInt(h.css("left").substring(0,h.css("left").length-2),10),b.playTopPos=b.frameBehindPlayerTopPos+parseInt((f.height()-k.height())/2,10),b.playLeftPos=parseInt((f.width()-k.width())/
 2,10),k.css({top:b.playTopPos+"px",left:b.playLeftPos+"px"}),b.previousTopPos=b.playTopPos+parseInt((k.height()-r.height())/2,10),b.previousLeftPos=b.imageLeftPos-r.width()-a.nextPrevAdditionalPadding,r.css({top:b.previousTopPos+"px",left:b.previousLeftPos+"px"}),b.nextTopPos=b.previousTopPos,b.nextLeftPos=b.imageLeftPos+(h.width()+2*a.imageBorderWidth)+a.nextPrevAdditionalPadding,n.css({top:b.nextTopPos+"px",left:b.nextLeftPos+"px"}),a.showHeadphone?(b.headphoneTopPos=0,b.headphoneLeftPos=parseInt(b.imageLeftPos+
 (h.width()+2*a.imageBorderWidth-L.width())/2,10),L.css({left:b.headphoneLeftPos+"px",top:b.headphoneTopPos+"px"})):L.css({display:"none"}),b.volumeTopPos=b.nextTopPos+Math.floor((n.height()-p.height())/2),b.volumeLeftPos=parseInt((b.previousLeftPos-(p.width()+u.width()+b.constantDistance))/2,10),p.css({top:b.volumeTopPos+"px",left:b.volumeLeftPos+"px"}),b.volumesliderTopPos=b.volumeTopPos+Math.floor((p.height()-u.height())/2),b.volumesliderLeftPos=b.volumeLeftPos+p.width()+b.constantDistance,u.css({top:b.volumesliderTopPos+
 "px",left:b.volumesliderLeftPos+"px"}),355>a.playerWidth?a.showTwitterBut&&--g:g=b.numberOfButtonsRightSide,b.smallButtonDistance=parseInt((a.playerWidth-b.nextLeftPos-n.width()-g*t.width())/(g+1),10),b.facebookTopPos=b.nextTopPos+Math.floor((n.height()-l.height())/2),b.facebookLeftPos=b.nextLeftPos+n.width()+b.smallButtonDistance,l.css({top:b.facebookTopPos+"px",left:b.facebookLeftPos+"px"}),a.showFacebookBut||(l.css({display:"none",width:0,height:0,padding:0,margin:0}),b.facebookLeftPos=b.nextLeftPos+
 n.width()),!a.showTwitterBut||355>a.playerWidth?(w.css({display:"none"}),b.twitterLeftPos=b.facebookLeftPos+l.width()-6):(w.css({display:"block"}),b.twitterTopPos=b.nextTopPos+Math.floor((n.height()-l.height())/2),b.twitterLeftPos=b.facebookLeftPos+l.width()+b.smallButtonDistance,w.css({top:b.twitterTopPos+"px",left:b.twitterLeftPos+"px"})),b.showhideplaylistTopPos=b.nextTopPos+Math.floor((n.height()-t.height())/2),b.showhideplaylistLeftPos=b.volumeLeftPos-b.smallButtonDistance,t.css({top:b.showhideplaylistTopPos+
 "px",left:b.showhideplaylistLeftPos+"px"}),y.width(e.width()+2*a.playerPadding),F.width(e.width()),B.width(a.playerWidth-2*a.playlistPadding),H.css({"background-position":a.playerWidth-2*a.playlistPadding-20+"px 50%"}),b.selectedCateg_total_images>a.numberOfThumbsPerScreen&&a.showPlaylist?(b.audio5_html5_sliderVertical.css({left:e.width()+2*a.playerPadding-b.audio5_html5_sliderVertical.width()-a.playlistPadding+"px"}),d(".thumbsHolder_ThumbOFF",e).css({width:e.width()+2*a.playerPadding-b.audio5_html5_sliderVertical.width()-
 2*a.playlistPadding-3+"px"})):d(".thumbsHolder_ThumbOFF",e).css({width:e.width()+2*a.playerPadding-2*a.playlistPadding+"px"}),J.css({width:parseInt(a.playerWidth-2*a.playlistPadding-50,10)+"px"})),a.playerWidth<d(window).width()&&e.parent().css({"float":b.origParentFloat,"padding-top":b.origParentPaddingTop,"padding-right":b.origParentPaddingRight,"padding-bottom":b.origParentPaddingBottom,"padding-left":b.origParentPaddingLeft}));445>a.playerWidth?(u.css({display:"none"}),p.css({display:"none"}),
 t.css({left:b.smallButtonDistance+"px"})):(u.css({display:"block"}),p.css({display:"block"}))},R=!1;d(window).on("resize",function(){doResizeNow=!0;-1!=E&&9==E&&0==b.windowWidth&&(doResizeNow=!1);b.windowWidth==d(window).width()?(doResizeNow=!1,a.windowCurOrientation!=window.orientation&&-1!=navigator.userAgent.indexOf("Android")&&(a.windowCurOrientation=window.orientation,doResizeNow=!0)):b.windowWidth=d(window).width();a.responsive&&doResizeNow&&(!1!==R&&clearTimeout(R),R=setTimeout(function(){M()},
 300))});a.responsive&&M()})};d.fn.audio5_html5.defaults={playerWidth:5E3,skin:"whiteControllers",initialVolume:.5,autoPlay:!0,loop:!0,playerPadding:0,playerBg:"#000000",volumeOffColor:"#454545",volumeOnColor:"#ffffff",timerColor:"#ffffff",songTitleColor:"#000000",radioStationColor:"#000000",frameBehindPlayerColor:"#000000",imageBorderWidth:4,imageBorderColor:"#000000",showFacebookBut:!0,facebookAppID:"499867206825745",facebookShareTitle:"Sticky Radio Player - Full Width Shoutcast and Icecast HTML5 Player",
 facebookShareDescription:"A top-notch responsive HTML5 Radio Player compatible with all major browsers and mobile devices.",showVolume:!0,showTwitterBut:!0,showRadioStation:!0,showTitle:!0,showPlaylistBut:!0,showPlaylist:!0,showPlaylistOnInit:!1,showNextPrevBut:!0,showHeadphone:!0,nextPrevAdditionalPadding:-5,autoHidePlayButton:!0,beneathTitleBackgroundColor_VisiblePlaylist:"#c55151",beneathTitleBackgroundOpacity_VisiblePlaylist:100,beneathTitleBackgroundColor_HiddenPlaylist:"#c55151",beneathTitleBackgroundOpacity_HiddenPlaylist:100,
 beneathTitleBackgroundBorderColor:"#000000",beneathTitleBackgroundBorderWidth:3,translateRadioStation:"Radio Station: ",translateSongTitle:"Now Playing: ",translateReadingData:"reading data...",translateAllRadioStations:"ALL RADIO STATIONS",playlistTopPos:5,playlistBgColor:"#c55151",playlistRecordBgOffColor:"#000000",playlistRecordBgOnColor:"#000000",playlistRecordBottomBorderOffColor:"#333333",playlistRecordBottomBorderOnColor:"#4d4d4d",playlistRecordTextOffColor:"#777777",playlistRecordTextOnColor:"#00b4f9",
 categoryRecordBgOffColor:"#000000",categoryRecordBgOnColor:"#252525",categoryRecordBottomBorderOffColor:"#2f2f2f",categoryRecordBottomBorderOnColor:"#2f2f2f",categoryRecordTextOffColor:"#777777",categoryRecordTextOnColor:"#00b4f9",numberOfThumbsPerScreen:7,playlistPadding:18,showCategories:!0,firstCateg:"ALL RADIO STATIONS",selectedCategBg:"#000000",selectedCategOffColor:"#FFFFFF",selectedCategOnColor:"#00b4f9",selectedCategMarginBottom:12,showSearchArea:!0,searchAreaBg:"#000000",searchInputText:" search...",
 searchInputBg:"#ffffff",searchInputBorderColor:"#333333",searchInputTextColor:"#333333",minButtonColor:"#FFFFFF",responsive:!0,showPlaylistNumber:!0,nowPlayingInterval:35,grabLastFmPhoto:!0,grabStreamnameAndGenre:!0,pathToAjaxFiles:"",noImageAvailable:"noimageavailable.jpg",lastFMApiKey:"",lastFMSecret:"",origWidth:0,isSliderInitialized:!1,isProgressInitialized:!1,isPlaylistSliderInitialized:!1}})(jQuery);
